/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WekaNenosiriRouteImport } from './routes/weka-nenosiri'
import { Route as WekaMchangoRouteImport } from './routes/weka-mchango'
import { Route as WasifuRouteImport } from './routes/wasifu'
import { Route as WanachamaKusubiriRouteImport } from './routes/wanachama-kusubiri'
import { Route as WanachamaRouteImport } from './routes/wanachama'
import { Route as VitendoVinavyosubiriRouteImport } from './routes/vitendo-vinavyosubiri'
import { Route as SajiliRouteImport } from './routes/sajili'
import { Route as SahauRouteImport } from './routes/sahau'
import { Route as RipotiRouteImport } from './routes/ripoti'
import { Route as MipangilioRouteImport } from './routes/mipangilio'
import { Route as MikopoRouteImport } from './routes/mikopo'
import { Route as MichangoYanguRouteImport } from './routes/michango-yangu'
import { Route as MichangoInayosubiriRouteImport } from './routes/michango-inayosubiri'
import { Route as MichangoRouteImport } from './routes/michango'
import { Route as MfukoKijamiiRouteImport } from './routes/mfuko-kijamii'
import { Route as MarejeshoRouteImport } from './routes/marejesho'
import { Route as KamatiMikopoRouteImport } from './routes/kamati-mikopo'
import { Route as IngiaRouteImport } from './routes/ingia'
import { Route as HistoriaYanguRouteImport } from './routes/historia-yangu'
import { Route as DashibodiOldRouteImport } from './routes/dashibodi-old'
import { Route as DashibodiRouteImport } from './routes/dashibodi'
import { Route as ArifaRouteImport } from './routes/arifa'
import { Route as AdminLogsRouteImport } from './routes/admin-logs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UongoziRipotiRouteImport } from './routes/uongozi/ripoti'
import { Route as UongoziMikopoRouteImport } from './routes/uongozi/mikopo'
import { Route as UongoziImportDataRouteImport } from './routes/uongozi/import-data'
import { Route as UkaguziMkopoLoanIdRouteImport } from './routes/ukaguzi-mkopo.$loanId'

const WekaNenosiriRoute = WekaNenosiriRouteImport.update({
  id: '/weka-nenosiri',
  path: '/weka-nenosiri',
  getParentRoute: () => rootRouteImport,
} as any)
const WekaMchangoRoute = WekaMchangoRouteImport.update({
  id: '/weka-mchango',
  path: '/weka-mchango',
  getParentRoute: () => rootRouteImport,
} as any)
const WasifuRoute = WasifuRouteImport.update({
  id: '/wasifu',
  path: '/wasifu',
  getParentRoute: () => rootRouteImport,
} as any)
const WanachamaKusubiriRoute = WanachamaKusubiriRouteImport.update({
  id: '/wanachama-kusubiri',
  path: '/wanachama-kusubiri',
  getParentRoute: () => rootRouteImport,
} as any)
const WanachamaRoute = WanachamaRouteImport.update({
  id: '/wanachama',
  path: '/wanachama',
  getParentRoute: () => rootRouteImport,
} as any)
const VitendoVinavyosubiriRoute = VitendoVinavyosubiriRouteImport.update({
  id: '/vitendo-vinavyosubiri',
  path: '/vitendo-vinavyosubiri',
  getParentRoute: () => rootRouteImport,
} as any)
const SajiliRoute = SajiliRouteImport.update({
  id: '/sajili',
  path: '/sajili',
  getParentRoute: () => rootRouteImport,
} as any)
const SahauRoute = SahauRouteImport.update({
  id: '/sahau',
  path: '/sahau',
  getParentRoute: () => rootRouteImport,
} as any)
const RipotiRoute = RipotiRouteImport.update({
  id: '/ripoti',
  path: '/ripoti',
  getParentRoute: () => rootRouteImport,
} as any)
const MipangilioRoute = MipangilioRouteImport.update({
  id: '/mipangilio',
  path: '/mipangilio',
  getParentRoute: () => rootRouteImport,
} as any)
const MikopoRoute = MikopoRouteImport.update({
  id: '/mikopo',
  path: '/mikopo',
  getParentRoute: () => rootRouteImport,
} as any)
const MichangoYanguRoute = MichangoYanguRouteImport.update({
  id: '/michango-yangu',
  path: '/michango-yangu',
  getParentRoute: () => rootRouteImport,
} as any)
const MichangoInayosubiriRoute = MichangoInayosubiriRouteImport.update({
  id: '/michango-inayosubiri',
  path: '/michango-inayosubiri',
  getParentRoute: () => rootRouteImport,
} as any)
const MichangoRoute = MichangoRouteImport.update({
  id: '/michango',
  path: '/michango',
  getParentRoute: () => rootRouteImport,
} as any)
const MfukoKijamiiRoute = MfukoKijamiiRouteImport.update({
  id: '/mfuko-kijamii',
  path: '/mfuko-kijamii',
  getParentRoute: () => rootRouteImport,
} as any)
const MarejeshoRoute = MarejeshoRouteImport.update({
  id: '/marejesho',
  path: '/marejesho',
  getParentRoute: () => rootRouteImport,
} as any)
const KamatiMikopoRoute = KamatiMikopoRouteImport.update({
  id: '/kamati-mikopo',
  path: '/kamati-mikopo',
  getParentRoute: () => rootRouteImport,
} as any)
const IngiaRoute = IngiaRouteImport.update({
  id: '/ingia',
  path: '/ingia',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaYanguRoute = HistoriaYanguRouteImport.update({
  id: '/historia-yangu',
  path: '/historia-yangu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashibodiOldRoute = DashibodiOldRouteImport.update({
  id: '/dashibodi-old',
  path: '/dashibodi-old',
  getParentRoute: () => rootRouteImport,
} as any)
const DashibodiRoute = DashibodiRouteImport.update({
  id: '/dashibodi',
  path: '/dashibodi',
  getParentRoute: () => rootRouteImport,
} as any)
const ArifaRoute = ArifaRouteImport.update({
  id: '/arifa',
  path: '/arifa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin-logs',
  path: '/admin-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UongoziRipotiRoute = UongoziRipotiRouteImport.update({
  id: '/uongozi/ripoti',
  path: '/uongozi/ripoti',
  getParentRoute: () => rootRouteImport,
} as any)
const UongoziMikopoRoute = UongoziMikopoRouteImport.update({
  id: '/uongozi/mikopo',
  path: '/uongozi/mikopo',
  getParentRoute: () => rootRouteImport,
} as any)
const UongoziImportDataRoute = UongoziImportDataRouteImport.update({
  id: '/uongozi/import-data',
  path: '/uongozi/import-data',
  getParentRoute: () => rootRouteImport,
} as any)
const UkaguziMkopoLoanIdRoute = UkaguziMkopoLoanIdRouteImport.update({
  id: '/ukaguzi-mkopo/$loanId',
  path: '/ukaguzi-mkopo/$loanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-logs': typeof AdminLogsRoute
  '/arifa': typeof ArifaRoute
  '/dashibodi': typeof DashibodiRoute
  '/dashibodi-old': typeof DashibodiOldRoute
  '/historia-yangu': typeof HistoriaYanguRoute
  '/ingia': typeof IngiaRoute
  '/kamati-mikopo': typeof KamatiMikopoRoute
  '/marejesho': typeof MarejeshoRoute
  '/mfuko-kijamii': typeof MfukoKijamiiRoute
  '/michango': typeof MichangoRoute
  '/michango-inayosubiri': typeof MichangoInayosubiriRoute
  '/michango-yangu': typeof MichangoYanguRoute
  '/mikopo': typeof MikopoRoute
  '/mipangilio': typeof MipangilioRoute
  '/ripoti': typeof RipotiRoute
  '/sahau': typeof SahauRoute
  '/sajili': typeof SajiliRoute
  '/vitendo-vinavyosubiri': typeof VitendoVinavyosubiriRoute
  '/wanachama': typeof WanachamaRoute
  '/wanachama-kusubiri': typeof WanachamaKusubiriRoute
  '/wasifu': typeof WasifuRoute
  '/weka-mchango': typeof WekaMchangoRoute
  '/weka-nenosiri': typeof WekaNenosiriRoute
  '/ukaguzi-mkopo/$loanId': typeof UkaguziMkopoLoanIdRoute
  '/uongozi/import-data': typeof UongoziImportDataRoute
  '/uongozi/mikopo': typeof UongoziMikopoRoute
  '/uongozi/ripoti': typeof UongoziRipotiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-logs': typeof AdminLogsRoute
  '/arifa': typeof ArifaRoute
  '/dashibodi': typeof DashibodiRoute
  '/dashibodi-old': typeof DashibodiOldRoute
  '/historia-yangu': typeof HistoriaYanguRoute
  '/ingia': typeof IngiaRoute
  '/kamati-mikopo': typeof KamatiMikopoRoute
  '/marejesho': typeof MarejeshoRoute
  '/mfuko-kijamii': typeof MfukoKijamiiRoute
  '/michango': typeof MichangoRoute
  '/michango-inayosubiri': typeof MichangoInayosubiriRoute
  '/michango-yangu': typeof MichangoYanguRoute
  '/mikopo': typeof MikopoRoute
  '/mipangilio': typeof MipangilioRoute
  '/ripoti': typeof RipotiRoute
  '/sahau': typeof SahauRoute
  '/sajili': typeof SajiliRoute
  '/vitendo-vinavyosubiri': typeof VitendoVinavyosubiriRoute
  '/wanachama': typeof WanachamaRoute
  '/wanachama-kusubiri': typeof WanachamaKusubiriRoute
  '/wasifu': typeof WasifuRoute
  '/weka-mchango': typeof WekaMchangoRoute
  '/weka-nenosiri': typeof WekaNenosiriRoute
  '/ukaguzi-mkopo/$loanId': typeof UkaguziMkopoLoanIdRoute
  '/uongozi/import-data': typeof UongoziImportDataRoute
  '/uongozi/mikopo': typeof UongoziMikopoRoute
  '/uongozi/ripoti': typeof UongoziRipotiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-logs': typeof AdminLogsRoute
  '/arifa': typeof ArifaRoute
  '/dashibodi': typeof DashibodiRoute
  '/dashibodi-old': typeof DashibodiOldRoute
  '/historia-yangu': typeof HistoriaYanguRoute
  '/ingia': typeof IngiaRoute
  '/kamati-mikopo': typeof KamatiMikopoRoute
  '/marejesho': typeof MarejeshoRoute
  '/mfuko-kijamii': typeof MfukoKijamiiRoute
  '/michango': typeof MichangoRoute
  '/michango-inayosubiri': typeof MichangoInayosubiriRoute
  '/michango-yangu': typeof MichangoYanguRoute
  '/mikopo': typeof MikopoRoute
  '/mipangilio': typeof MipangilioRoute
  '/ripoti': typeof RipotiRoute
  '/sahau': typeof SahauRoute
  '/sajili': typeof SajiliRoute
  '/vitendo-vinavyosubiri': typeof VitendoVinavyosubiriRoute
  '/wanachama': typeof WanachamaRoute
  '/wanachama-kusubiri': typeof WanachamaKusubiriRoute
  '/wasifu': typeof WasifuRoute
  '/weka-mchango': typeof WekaMchangoRoute
  '/weka-nenosiri': typeof WekaNenosiriRoute
  '/ukaguzi-mkopo/$loanId': typeof UkaguziMkopoLoanIdRoute
  '/uongozi/import-data': typeof UongoziImportDataRoute
  '/uongozi/mikopo': typeof UongoziMikopoRoute
  '/uongozi/ripoti': typeof UongoziRipotiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-logs'
    | '/arifa'
    | '/dashibodi'
    | '/dashibodi-old'
    | '/historia-yangu'
    | '/ingia'
    | '/kamati-mikopo'
    | '/marejesho'
    | '/mfuko-kijamii'
    | '/michango'
    | '/michango-inayosubiri'
    | '/michango-yangu'
    | '/mikopo'
    | '/mipangilio'
    | '/ripoti'
    | '/sahau'
    | '/sajili'
    | '/vitendo-vinavyosubiri'
    | '/wanachama'
    | '/wanachama-kusubiri'
    | '/wasifu'
    | '/weka-mchango'
    | '/weka-nenosiri'
    | '/ukaguzi-mkopo/$loanId'
    | '/uongozi/import-data'
    | '/uongozi/mikopo'
    | '/uongozi/ripoti'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-logs'
    | '/arifa'
    | '/dashibodi'
    | '/dashibodi-old'
    | '/historia-yangu'
    | '/ingia'
    | '/kamati-mikopo'
    | '/marejesho'
    | '/mfuko-kijamii'
    | '/michango'
    | '/michango-inayosubiri'
    | '/michango-yangu'
    | '/mikopo'
    | '/mipangilio'
    | '/ripoti'
    | '/sahau'
    | '/sajili'
    | '/vitendo-vinavyosubiri'
    | '/wanachama'
    | '/wanachama-kusubiri'
    | '/wasifu'
    | '/weka-mchango'
    | '/weka-nenosiri'
    | '/ukaguzi-mkopo/$loanId'
    | '/uongozi/import-data'
    | '/uongozi/mikopo'
    | '/uongozi/ripoti'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-logs'
    | '/arifa'
    | '/dashibodi'
    | '/dashibodi-old'
    | '/historia-yangu'
    | '/ingia'
    | '/kamati-mikopo'
    | '/marejesho'
    | '/mfuko-kijamii'
    | '/michango'
    | '/michango-inayosubiri'
    | '/michango-yangu'
    | '/mikopo'
    | '/mipangilio'
    | '/ripoti'
    | '/sahau'
    | '/sajili'
    | '/vitendo-vinavyosubiri'
    | '/wanachama'
    | '/wanachama-kusubiri'
    | '/wasifu'
    | '/weka-mchango'
    | '/weka-nenosiri'
    | '/ukaguzi-mkopo/$loanId'
    | '/uongozi/import-data'
    | '/uongozi/mikopo'
    | '/uongozi/ripoti'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLogsRoute: typeof AdminLogsRoute
  ArifaRoute: typeof ArifaRoute
  DashibodiRoute: typeof DashibodiRoute
  DashibodiOldRoute: typeof DashibodiOldRoute
  HistoriaYanguRoute: typeof HistoriaYanguRoute
  IngiaRoute: typeof IngiaRoute
  KamatiMikopoRoute: typeof KamatiMikopoRoute
  MarejeshoRoute: typeof MarejeshoRoute
  MfukoKijamiiRoute: typeof MfukoKijamiiRoute
  MichangoRoute: typeof MichangoRoute
  MichangoInayosubiriRoute: typeof MichangoInayosubiriRoute
  MichangoYanguRoute: typeof MichangoYanguRoute
  MikopoRoute: typeof MikopoRoute
  MipangilioRoute: typeof MipangilioRoute
  RipotiRoute: typeof RipotiRoute
  SahauRoute: typeof SahauRoute
  SajiliRoute: typeof SajiliRoute
  VitendoVinavyosubiriRoute: typeof VitendoVinavyosubiriRoute
  WanachamaRoute: typeof WanachamaRoute
  WanachamaKusubiriRoute: typeof WanachamaKusubiriRoute
  WasifuRoute: typeof WasifuRoute
  WekaMchangoRoute: typeof WekaMchangoRoute
  WekaNenosiriRoute: typeof WekaNenosiriRoute
  UkaguziMkopoLoanIdRoute: typeof UkaguziMkopoLoanIdRoute
  UongoziImportDataRoute: typeof UongoziImportDataRoute
  UongoziMikopoRoute: typeof UongoziMikopoRoute
  UongoziRipotiRoute: typeof UongoziRipotiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weka-nenosiri': {
      id: '/weka-nenosiri'
      path: '/weka-nenosiri'
      fullPath: '/weka-nenosiri'
      preLoaderRoute: typeof WekaNenosiriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weka-mchango': {
      id: '/weka-mchango'
      path: '/weka-mchango'
      fullPath: '/weka-mchango'
      preLoaderRoute: typeof WekaMchangoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wasifu': {
      id: '/wasifu'
      path: '/wasifu'
      fullPath: '/wasifu'
      preLoaderRoute: typeof WasifuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wanachama-kusubiri': {
      id: '/wanachama-kusubiri'
      path: '/wanachama-kusubiri'
      fullPath: '/wanachama-kusubiri'
      preLoaderRoute: typeof WanachamaKusubiriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wanachama': {
      id: '/wanachama'
      path: '/wanachama'
      fullPath: '/wanachama'
      preLoaderRoute: typeof WanachamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitendo-vinavyosubiri': {
      id: '/vitendo-vinavyosubiri'
      path: '/vitendo-vinavyosubiri'
      fullPath: '/vitendo-vinavyosubiri'
      preLoaderRoute: typeof VitendoVinavyosubiriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sajili': {
      id: '/sajili'
      path: '/sajili'
      fullPath: '/sajili'
      preLoaderRoute: typeof SajiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sahau': {
      id: '/sahau'
      path: '/sahau'
      fullPath: '/sahau'
      preLoaderRoute: typeof SahauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ripoti': {
      id: '/ripoti'
      path: '/ripoti'
      fullPath: '/ripoti'
      preLoaderRoute: typeof RipotiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mipangilio': {
      id: '/mipangilio'
      path: '/mipangilio'
      fullPath: '/mipangilio'
      preLoaderRoute: typeof MipangilioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mikopo': {
      id: '/mikopo'
      path: '/mikopo'
      fullPath: '/mikopo'
      preLoaderRoute: typeof MikopoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/michango-yangu': {
      id: '/michango-yangu'
      path: '/michango-yangu'
      fullPath: '/michango-yangu'
      preLoaderRoute: typeof MichangoYanguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/michango-inayosubiri': {
      id: '/michango-inayosubiri'
      path: '/michango-inayosubiri'
      fullPath: '/michango-inayosubiri'
      preLoaderRoute: typeof MichangoInayosubiriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/michango': {
      id: '/michango'
      path: '/michango'
      fullPath: '/michango'
      preLoaderRoute: typeof MichangoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfuko-kijamii': {
      id: '/mfuko-kijamii'
      path: '/mfuko-kijamii'
      fullPath: '/mfuko-kijamii'
      preLoaderRoute: typeof MfukoKijamiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marejesho': {
      id: '/marejesho'
      path: '/marejesho'
      fullPath: '/marejesho'
      preLoaderRoute: typeof MarejeshoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamati-mikopo': {
      id: '/kamati-mikopo'
      path: '/kamati-mikopo'
      fullPath: '/kamati-mikopo'
      preLoaderRoute: typeof KamatiMikopoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingia': {
      id: '/ingia'
      path: '/ingia'
      fullPath: '/ingia'
      preLoaderRoute: typeof IngiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia-yangu': {
      id: '/historia-yangu'
      path: '/historia-yangu'
      fullPath: '/historia-yangu'
      preLoaderRoute: typeof HistoriaYanguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashibodi-old': {
      id: '/dashibodi-old'
      path: '/dashibodi-old'
      fullPath: '/dashibodi-old'
      preLoaderRoute: typeof DashibodiOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashibodi': {
      id: '/dashibodi'
      path: '/dashibodi'
      fullPath: '/dashibodi'
      preLoaderRoute: typeof DashibodiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arifa': {
      id: '/arifa'
      path: '/arifa'
      fullPath: '/arifa'
      preLoaderRoute: typeof ArifaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-logs': {
      id: '/admin-logs'
      path: '/admin-logs'
      fullPath: '/admin-logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uongozi/ripoti': {
      id: '/uongozi/ripoti'
      path: '/uongozi/ripoti'
      fullPath: '/uongozi/ripoti'
      preLoaderRoute: typeof UongoziRipotiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uongozi/mikopo': {
      id: '/uongozi/mikopo'
      path: '/uongozi/mikopo'
      fullPath: '/uongozi/mikopo'
      preLoaderRoute: typeof UongoziMikopoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uongozi/import-data': {
      id: '/uongozi/import-data'
      path: '/uongozi/import-data'
      fullPath: '/uongozi/import-data'
      preLoaderRoute: typeof UongoziImportDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukaguzi-mkopo/$loanId': {
      id: '/ukaguzi-mkopo/$loanId'
      path: '/ukaguzi-mkopo/$loanId'
      fullPath: '/ukaguzi-mkopo/$loanId'
      preLoaderRoute: typeof UkaguziMkopoLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLogsRoute: AdminLogsRoute,
  ArifaRoute: ArifaRoute,
  DashibodiRoute: DashibodiRoute,
  DashibodiOldRoute: DashibodiOldRoute,
  HistoriaYanguRoute: HistoriaYanguRoute,
  IngiaRoute: IngiaRoute,
  KamatiMikopoRoute: KamatiMikopoRoute,
  MarejeshoRoute: MarejeshoRoute,
  MfukoKijamiiRoute: MfukoKijamiiRoute,
  MichangoRoute: MichangoRoute,
  MichangoInayosubiriRoute: MichangoInayosubiriRoute,
  MichangoYanguRoute: MichangoYanguRoute,
  MikopoRoute: MikopoRoute,
  MipangilioRoute: MipangilioRoute,
  RipotiRoute: RipotiRoute,
  SahauRoute: SahauRoute,
  SajiliRoute: SajiliRoute,
  VitendoVinavyosubiriRoute: VitendoVinavyosubiriRoute,
  WanachamaRoute: WanachamaRoute,
  WanachamaKusubiriRoute: WanachamaKusubiriRoute,
  WasifuRoute: WasifuRoute,
  WekaMchangoRoute: WekaMchangoRoute,
  WekaNenosiriRoute: WekaNenosiriRoute,
  UkaguziMkopoLoanIdRoute: UkaguziMkopoLoanIdRoute,
  UongoziImportDataRoute: UongoziImportDataRoute,
  UongoziMikopoRoute: UongoziMikopoRoute,
  UongoziRipotiRoute: UongoziRipotiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
